- hosts: localhost
  vars:
    root_cert: "{{ lookup('file', '{{ root_cert_path }}') }}"
    intermediate_cert: "{{ lookup('file', '{{ intermediate_cert_path }}') }}"
    api_cer: "{{ lookup('file', '{{ api_cert_path }}') }}"
    apps_cer: "{{ lookup('file', '{{ apps_cert_path }}') }}"
    api_key: "{{ lookup('file', '{{ api_cert_key_path }}') }}"
    apps_key: "{{ lookup('file', '{{ apps_cert_key_path }}') }}"
  roles:
    - api-app-ssl