---
- hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_prompt:
    - name: cluster_name
      prompt: Enter Cluster name
      private: no
  tasks:
  - name: Create project
    k8s:
      api_version: v1
      kind: Namespace
      name: "{{ item.project_name }}"
      state: present
      verify_ssl: no
    loop: "{{ lookup('vars',cluster_name).projects }}"