domain_name: os.ergo.com
cluster_name: ocpa2
VMWARE_HOST: esxte00900.servers.ergodev
datacenter: TLN
datastore: TLN-C2-SC-SK3-N6fe
datastore_cluster: LDSC-TLN-C2-SC-SK3
vmware_cluster: TLN-C2-SC
vcenter_cluster: TLN-C2-SC
#rhcos_template: "rhcos-4.7.7-x86_64-vmware.x86_64-{{ datacenter }}"
rhcos_template: "rhcos-4.8.14-x86_64-vmware.x86_64-{{ datacenter }}"
vm_network: "dvPG-VM-10.58.127.0-TLN-01"
parent_folder: "/TLN/vm/Abnahme/Openshift Container Platform (OCP)"
vmare_cred_path: "secrets/ergodev_prod_bz/ergodev_vmware_cred.yaml"
vm_rootdisk_size: 120
machine_cidr: "10.58.127.0/24"
network_utility_ip: 10.58.127.101
bootstrap_ip: 10.58.127.100
master_ips: 10.58.127.102,10.58.127.103,10.58.127.104
infra_ips: 10.58.127.105,10.58.127.106,10.58.127.107
worker_ips: 10.58.127.108,10.58.127.109,10.58.127.110
network_utility_netmask: 255.255.255.0
network_utility_gateway: 10.58.127.1
network_utility_dns_server: "{{ dns1 }}"
bootstrap_vm_name: "{{ cluster_name }}-bootstrap"
master_vm_names: "OCPTEBA11011,OCPTEBA11022,OCPTEBA11031"
infra_vm_names: "OCPTEBA16011,OCPTEBA16022,OCPTEBA16031"
worker_vm_names: "OCPTEBA12011,OCPTEBA12022,OCPTEBA12031"
pull_secret_path: "secrets/ergodev_prod_bz/pull_secret_{{ cluster_name }}.yaml"
authorized_ssh_keys_path: "secrets/ergodev_prod_bz/LC_OCP_OPS_A2_ssh_keys.yaml"
auth_private_key_path: "secrets/ergodev_prod_bz/LC_OCP_OPS_A2_ssh_private_keys.yaml"
registry_fqdn: container-proxy.services.ergodev
mirror_registry: "{{ registry_fqdn }}/openshift-release-dev/ocp-release"
mirror_registry_dev: "{{ registry_fqdn }}/openshift-release-dev/ocp-v4.0-art-dev"
haproxy_image: "{{ registry_fqdn }}/haproxytech/haproxy:latest"
httpd_image: "{{ registry_fqdn }}/rhel8/httpd-24:latest"
cluster_network: 10.128.0.0/14
host_prefix: 23
service_network: 172.30.0.0/16
master_vm_memory: 16384
worker_vm_memory: 16384
infra_vm_memory: 16384
master_vm_cpus: 4
worker_vm_cpus: 4
infra_vm_cpus: 4
domainname: lindmzn.ergodev
dns1: 10.56.238.20
dns2: 10.56.238.21
api_url: "https://api.{{ cluster_name }}.{{ domain_name }}:6443"
custom_url: "console.apps.{{ cluster_name }}.{{ domain_name }}"
ntpserver1: server 10.56.238.162 iburst
ntpserver2: server 10.56.238.146 iburst
# LDAP setup
bindDN: "LC_OCP_LDAP"
ldap_url: "ldaps://corp.ergodev:636/DC=CORP,DC=ERGODEV?sAMAccountName"
bindPassword_path: "secrets/ergodev_prod_bz/bindpassword.yaml"
# LDAP Group Sync Cronjob

# #Temporary
ldap_sync_url: "ldaps://corp.ergodev:636"
groups_baseDN: "OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev"
users_baseDN: "DC=corp,DC=ergodev"
whitelist_groups: |
      CN=GFE_OCP_A2_CLUSTER_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev
      CN=GFE_OCP_A2_CLUSTER_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev
      CN=GFE_OCP_A2_TEST_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev
      CN=GFE_OCP_A2_TEST_EDIT,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev
      CN=GFE_OCP_A2_TEST_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev
ldap_sync_schedule: "*/15 * * * *"
ldap_sync_cli: "{{ registry_fqdn }}/openshift4/ose-cli:latest"
cluster_admin_group: GFE_OCP_A2_CLUSTER_ADMIN
cluster_reader_group: GFE_OCP_A2_CLUSTER_VIEW
#
#
###Certificates
root_cert_path: "certificates/CAs/root_ca_ergodev.crt"
intermediate_cert_path: "certificates/CAs/sub_ca_ergodev.crt"
api_cert_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.csr.cer"
apps_cert_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.csr.cer"
api_cert_key_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.key"
apps_cert_key_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.key"
quota_cpu: "5"
quota_memory: 30Gi
quota_pods: "100"
quota_configmaps: "20"
quota_persistentvolumeclaims: "20"
quota_replicationcontrollers: "80"
quota_requests_storage: 50Gi
quota_services: "30"
container_max_memory: 2Gi
container_min_memory: 128Mi
container_max_cpu: 4Gi
container_min_cpu: 100m
container_default_cpu: 200m
container_default_memory: 512Mi
container_defaultRequest_cpu: 1m
container_defaultRequest_memory: 256Mi
pod_max_memory: 8Gi
pod_min_memory: 6Mi
pod_max_cpu: 2000m
pod_min_cpu: 1m
vsphere_disk_format: zeroedthick
vsphere_sc_name: thick

##HaProxy variables
bootstrap:
 - name: ocpa2-bootstrap
   ip: 10.58.127.100 

controlplane:
 - name: OCPTEBA11011.ocpa2.os.ergo.com
   ip: 10.58.127.102
 - name: OCPTEBA11022.ocpa2.os.ergo.com
   ip: 10.58.127.103
 - name: OCPTEBA11031.ocpa2.os.ergo.com
   ip: 10.58.127.104

compute:
 - name: OCPTEBA12011.ocpa2.os.ergo.com
   ip: 10.58.127.108
 - name: OCPTEBA12022.ocpa2.os.ergo.com
   ip: 10.58.127.109
 - name: OCPTEBA12031.ocpa2.os.ergo.com
   ip: 10.58.127.110

infra:
 - name: OCPTEBA16011.ocpa2.os.ergo.com
   ip: 10.58.127.105
 - name: OCPTEBA16022.ocpa2.os.ergo.com
   ip: 10.58.127.106
 - name: OCPTEBA16031.ocpa2.os.ergo.com
   ip: 10.58.127.107

vip_ip: 10.58.67.60
interface_name: 'ens192'
virtual_router_id: '124'

#Replace unhealthy node or create new node
replace_node_name: ''
new_node_name: ''
ip_address: ''
node_memory_mb: ''
node_cpu: ''
old_ignition_file: './files/old_worker.ign'
ignition_file: './files/worker.ign'

#ClusterLogForwarder Configuration for CLM/ALM
alm:
  alm_ca_bundle_cert: "{{lookup ('file', 'certificates/ocpa2/alm-ca-bundle-cert')}}"
  alm_username_password: "secrets/ergodev_prod_bz/alm-elk-username-password.yaml"
  alm_endpoint: 10.4.133.118
  alm_port: 9200
  label: ocpa1
  namespace: a1-ifrs17-itbb

# Cluster upgrade vars
raw_proxy_url: https://nexus.services.ergodev/repository/raw-proxy
# #Cluster health check variable
technical_user: 'secrets/ergodev_prod_bz/LC_OCP_OPS_A2.yaml'
installer_artifacts_url: '{{ raw_proxy_url }}/pub/openshift-v4/clients/ocp'
nexus_cred_path: 'secrets//ergodev_prod_bz/LC_NXRM_OSCP_A_001.yaml'
namespace: demo
# Egress router
source:
  egress_ip1: 10.58.127.118
  egress_ip2: 10.58.127.119
  egress_gateway: 10.4.154.1
egress_destination: |
      25 tcp 10.4.151.223 25
      26 tcp 10.4.151.224 25
egress_service_ports: |
  - name: egress-smtp
    port: 25
    protocol: TCP
    targetPort: 25
  - name: egress-smtp2
    port: 26
    protocol: TCP
