domain_name: services.ergodev
cluster_name: ocpa1
VMWARE_HOST: esxte00900.servers.ergodev
datacenter: TE0
datastore: TE0-C7-SC-SK3-N12b6-S
datastore_cluster: LDSC-TE0-C7-SC-SK3
vmware_cluster: TE0-C7-SC
vcenter_cluster: TE0-C7-SC
rhcos_template: "rhcos-4.8.14-x86_64-vmware.x86_64-{{ datacenter }}"
vm_network: "dvPG-VM-10.4.154.0-TE0-01"
parent_folder: "/TE0/vm/Abnahme/Openshift Container Platform (OCP)"
vmare_cred_path: "secrets/ergodev_prod/ergodev_vmware_cred.yaml"
vm_rootdisk_size: 120
machine_cidr: "10.4.154.0/24"
network_utility_ip: 10.4.154.96
bootstrap_ip: 10.4.154.95
master_ips: 10.4.154.119,10.4.154.139,10.4.154.140
worker_ips: 10.4.154.156,10.4.154.159,10.4.154.162,10.4.154.163,10.4.154.164,10.4.154.171
infra_ips: 10.4.154.141,10.4.154.144,10.4.154.145
network_utility_netmask: 255.255.255.0
network_utility_gateway: 10.4.154.1
network_utility_dns_server: 10.4.116.30
bootstrap_vm_name: "{{ cluster_name }}-bootstrap"
master_vm_names: "OCPTE0A11011,OCPTE0A11022,OCPTE0A11031"
worker_vm_names: "OCPTE0A12011,OCPTE0A12022,OCPTE0A12031,OCPTE0A12042,OCPTE0A12051,OCPTE0A12062"
infra_vm_names: "OCPTE0A16011,OCPTE0A16022,OCPTE0A16031"
pull_secret_path: "secrets/ergodev_prod/pull_secret_{{ cluster_name }}.yaml"
authorized_ssh_keys_path: "secrets/ergodev_prod/LC_OCP_OPS_D1_ssh_private_keys.yaml"
auth_private_key_path: "secrets/ergodev_prod/LC_OCP_OPS_A1_ssh_private_keys.yaml"
registry_fqdn: "container-proxy.services.ergodev"
mirror_registry: "{{ registry_fqdn }}/openshift-release-dev/ocp-release"
mirror_registry_dev: "{{ registry_fqdn }}/openshift-release-dev/ocp-v4.0-art-dev"
haproxy_image: "{{ registry_fqdn }}/haproxytech/haproxy:latest"
httpd_image: "{{ registry_fqdn }}/rhel8/httpd-24:latest"
cluster_network: 10.128.0.0/14
host_prefix: 23
service_network: 172.30.0.0/16
master_vm_memory: 16384
worker_vm_memory: 65536
infra_vm_memory: 16384
master_vm_cpus: 8
worker_vm_cpus: 6
infra_vm_cpus: 8
domainname: linux.ergodev
dns1: 10.4.116.30
dns2: 10.4.113.46
api_url: "https://api.{{ cluster_name }}.{{ domain_name }}:6443"
custom_url: "console.apps.{{ cluster_name }}.{{ domain_name }}"
ntpserver1: server 10.4.133.191 iburst
ntpserver2: server 10.4.133.192 iburst

# LDAP setup
bindDN: "LC_OCP_LDAP"
ldap_url: "ldaps://corp.ergodev:636/DC=CORP,DC=ERGODEV?sAMAccountName"
bindPassword_path: "secrets/ergodev_prod/bindpassword.yaml"

# LDAP Group Sync Cronjob
ldap_sync_url: "ldaps://corp.ergodev:636"
groups_baseDN: "OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev"
#users_baseDN: "OU=Administration,OU=.Common,DC=corp,DC=ergodev"
users_baseDN: "OU=DC=corp,DC=ergodev"
whitelist_groups: |
      CN=GFE_OCP_A1_CLUSTER_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev
      CN=GFE_OCP_A1_CLUSTER_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev  
      CN=GFE_OCP_A1_TEST_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev    
      CN=GFE_OCP_A1_TEST_EDIT,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev     
      CN=GFE_OCP_A1_TEST_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergodev
ldap_sync_schedule: "*/15 * * * *"
ldap_sync_cli: "{{ registry_fqdn }}/openshift4/ose-cli:latest"
cluster_admin_group: GFE_OCP_A1_CLUSTER_ADMIN
cluster_reader_group: GFE_OCP_A1_CLUSTER_VIEW
##Certificates
root_cert_path: "certificates/CAs/root_ca_ergodev.crt"
intermediate_cert_path: "certificates/CAs/sub_ca_ergodev.crt"
api_cert_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.csr.cer"
apps_cert_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.csr.cer"
api_cert_key_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.key"
apps_cert_key_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.key"
quota_cpu: "5"
quota_memory: 30Gi
quota_pods: "100"
quota_configmaps: "20"
quota_persistentvolumeclaims: "0"
quota_replicationcontrollers: "80"
quota_requests_storage: 50Gi
quota_services: "30"
container_max_memory: 2Gi
container_min_memory: 128Mi
container_max_cpu: 4Gi
container_min_cpu: 100m
container_default_cpu: 200m
container_default_memory: 512Mi
container_defaultRequest_cpu: 1m
container_defaultRequest_memory: 256Mi
pod_max_memory: 8Gi
pod_min_memory: 6Mi
pod_max_cpu: 2000m
pod_min_cpu: 1m
vsphere_disk_format: zeroedthick
vsphere_sc_name: thick

##HaProxy variables
bootstrap:
 - name: ocpa1-bootstrap
   ip: 10.4.154.95

controlplane:
 - name: OCPTE0A11011.ocpa1.services.ergodev
   ip: 10.4.154.119
 - name: OCPTE0A11022.ocpa1.services.ergodev
   ip: 10.4.154.139
 - name: OCPTE0A11031.ocpa1.services.ergodev
   ip: 10.4.154.140

compute:
 - name: OCPTE0A12011.ocpa1.services.ergodev
   ip: 10.4.154.156
 - name: OCPTE0A12022.ocpa1.services.ergodev
   ip: 10.4.154.159
 - name: OCPTE0A12031.ocpa1.services.ergodev
   ip: 10.4.154.162
 - name: OCPTE0A12042.ocpa1.services.ergodev
   ip: 10.4.154.163
 - name: OCPTE0A12051.ocpa1.services.ergodev
   ip: 10.4.154.164
 - name: OCPTE0A12062.ocpa1.services.ergodev
   ip: 10.4.154.171

infra:
 - name: OCPTE0A16011.ocpa1.services.ergodev
   ip: 10.4.154.141
 - name: OCPTE0A16022.ocpa1.services.ergodev
   ip: 10.4.154.144
 - name: OCPTE0A16031.ocpa1.services.ergodev
   ip: 10.4.154.145

vip_ip: 10.4.133.126
interface_name: 'ens192'
virtual_router_id: '114'

#Replace unhealthy node or create new node
replace_node_name: ''
new_node_name: ''
ip_address: ''
node_memory_mb: ''
node_cpu: ''
old_ignition_file: './files/old_worker.ign'
ignition_file: './files/worker.ign'

#ClusterLogForwarder Configuration for CLM/ALM
alm:
  alm_ca_bundle_cert: "{{lookup ('file', 'certificates/ocpa1/alm-ca-bundle-cert')}}"
  alm_username_password: "secrets/ergodev_prod/alm-elk-username-password.yaml"
  alm_endpoint: 10.4.133.118
  alm_port: 9200
  label: ocpa1
  namespace: a1-ifrs17-itbb
# Cluster upgrade vars
raw_proxy_url: https://nexus.services.ergodev/repository/raw-proxy
#Cluster health check variable
technical_user: 'secrets/ergodev_prod/LC_OCP_OPS_A1.yaml'
installer_artifacts_url: '{{ raw_proxy_url }}/pub/openshift-v4/clients/ocp'
nexus_cred_path: 'secrets/ergodev_prod/LC_NXRM_OSCP_A_001.yaml'

# Egress router
source:
  egress_ip1: 10.4.154.172
  egress_ip2: 10.4.154.177
  egress_gateway: 10.4.154.1
egress_destination: |
      25 tcp 10.4.151.223 25
      26 tcp 10.4.151.224 25
egress_service_ports: |
  - name: egress-smtp
    port: 25
    protocol: TCP
    targetPort: 25
  - name: egress-smtp2
    port: 26
    protocol: TCP

