domain_name: services.ergo
cluster_name: ocpp2
VMWARE_HOST: 
datacenter: 
datastore: 
vmware_cluster:  
vcenter_cluster: 
rhcos_template: "rhcos-4.8.14-x86_64-vmware.x86_64-{{ datacenter }}"
vm_network: ""
parent_folder: ""
vmare_cred_path: "secrets/ergo_prod_bz/ergo_vmware_cred.yaml"
vm_rootdisk_size: 120
machine_cidr: "10.58.191.0/24"
network_utility_ip: 10.58.191.101
bootstrap_ip: 10.58.191.100
master_ips: 10.58.191.102,10.58.191.103,10.58.191.104
worker_ips: 10.58.191.108,10.58.191.109,10.58.191.110
infra_ips: 10.58.191.105,10.58.191.106,10.58.191.107
network_utility_netmask: 255.255.255.0
network_utility_gateway: 10.58.191.1
network_utility_dns_server: "{{ dns1 }}"
bootstrap_vm_name: "{{ cluster_name }}-bootstrap"
master_vm_names: "OCPPEBP11011.ocpp2.os.ergo.com,OCPPEBP11022.ocpp2.os.ergo.com,OCPPEBP11031.ocpp2.os.ergo.com"
worker_vm_names: "OCPPEBP12011.ocpp2.os.ergo.com,OCPPEBP12022.ocpp2.os.ergo.com,OCPPEBP12031.ocpp2.os.ergo.com"
infra_vm_names: "OCPPEBP16011.ocpp2.os.ergo.com,OCPPEBP16022.ocpp2.os.ergo.com,OCPPEBP16031.ocpp2.os.ergo.com"
pull_secret_path: "secrets/ergo_prod_bz/pull_secret_ocpp2.yaml"
authorized_ssh_keys_path: "secrets/ergo_prod_bz/LC_OCP_OPS_P2_ssh_keys.yaml"
auth_private_key_path: "secrets/ergo_prod_bz/LC_OCP_OPS_P2_ssh_private_keys.yaml"
registry_fqdn: container-proxy.services.ergo
mirror_registry: "{{ registry_fqdn }}/openshift-release-dev/ocp-release"
mirror_registry_dev: "{{ registry_fqdn }}/openshift-release-dev/ocp-v4.0-art-dev"
haproxy_image: "{{ registry_fqdn }}/haproxytech/haproxy:latest"
httpd_image: "{{ registry_fqdn }}/rhel8/httpd-24:latest"
cluster_network: 10.128.0.0/14
host_prefix: 23
service_network: 172.30.0.0/16
master_vm_memory: 16384
worker_vm_memory: 65536
infra_vm_memory: 16384
master_vm_cpus: 8
worker_vm_cpus: 6
infra_vm_cpus: 8
domainname: linux.ergo
dns1: 10.57.238.20
dns2: 10.57.238.21
api_url: "https://api.{{ cluster_name }}.{{ domain_name }}:6443"
custom_url: "console.apps.{{ cluster_name }}.{{ domain_name }}"
ntpserver1: server 10.49.90.181 iburst
ntpserver2: server 10.49.90.182 iburst

# LDAP setup
bindDN: "LC_OCP_LDAP"
ldap_url: "ldaps://corp.ergo:636/DC=CORP,DC=ERGO?sAMAccountName"
bindPassword_path: "secrets/ergo_prod/bindpassword.yaml"

# LDAP Group Sync Cronjob
ldap_sync_url: "ldaps://corp.ergo:636"
groups_baseDN: "OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo"
#users_baseDN: "OU=Administration,OU=.Common,DC=corp,DC=ergo"
users_baseDN: "DC=corp,DC=ergo"
whitelist_groups: |
      CN=GFE_OCP_P2_CLUSTER_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo
      CN=GFE_OCP_P2_CLUSTER_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo	
      CN=GFE_OCP_P2_TEST_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo	
      CN=GFE_OCP_P2_TEST_EDIT,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo	
      CN=GFE_OCP_P2_TEST_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo
ldap_sync_schedule: "*/15 * * * *"
ldap_sync_cli: "{{ registry_fqdn }}/openshift4/ose-cli:latest"
cluster_admin_group: GFE_OCP_P2_CLUSTER_ADMIN
cluster_reader_group: GFE_OCP_P2_CLUSTER_VIEW
##Certificates
root_cert_path: "certificates/CAs/root_ca_ergo.cer"
intermediate_cert_path: "certificates/CAs/sub_ca_ergo.cer"
api_cert_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.csr.cer"
apps_cert_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.csr.cer"
api_cert_key_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.key"
apps_cert_key_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.key"
quota_cpu: "5"
quota_memory: 30Gi
quota_pods: "100"
quota_configmaps: "20"
quota_persistentvolumeclaims: "0"
quota_replicationcontrollers: "80"
quota_requests_storage: 50Gi
quota_services: "30"
container_max_memory: 2Gi
container_min_memory: 128Mi
container_max_cpu: 4Gi
container_min_cpu: 100m
container_default_cpu: 200m
container_default_memory: 512Mi
container_defaultRequest_cpu: 1m
container_defaultRequest_memory: 256Mi
pod_max_memory: 8Gi
pod_min_memory: 6Mi
pod_max_cpu: 2000m
pod_min_cpu: 1m
vsphere_disk_format: zeroedthick
vsphere_sc_name: thick

##HaProxy variables
bootstrap:
 - name: ocpp2-bootstrap
   ip: 10.58.191.100
controlplane:
 - name: OCPPEBP11011.ocpp2.os.ergo.com
   ip: 10.58.191.102
 - name: OCPPEBP11022.ocpp2.os.ergo.com
   ip: 10.58.191.103
 - name: OCPPEBP11031.ocpp2.os.ergo.com
   ip: 10.58.191.104
compute:
 - name: OCPPEBP12011.ocpp2.os.ergo.com
   ip: 10.58.191.108
 - name: OCPPEBP12022.ocpp2.os.ergo.com
   ip: 10.58.191.109
 - name: OCPPEBP12031.ocpp2.os.ergo.com
   ip: 10.58.191.110

infra:
 - name: OCPPEBP16011.ocpp2.os.ergo.com
   ip: 10.58.191.105
 - name: OCPPEBP16022.ocpp2.os.ergo.com
   ip: 10.58.191.106
 - name: OCPPEBP16031.ocpp2.os.ergo.com
   ip: 10.58.191.107

vip_ip: 10.58.191.119
interface_name: 'ens192'
virtual_router_id: '115'

#Replace unhealthy node or create new node
replace_node_name: ''
new_node_name: ''
ip_address: ''
node_memory_mb: ''
node_cpu: ''
old_ignition_file: './files/old_worker.ign'
ignition_file: './files/worker.ign'

#ClusterLogForwarder Configuration for CLM/ALM
alm:
  alm_ca_bundle_cert: "{{lookup ('file', 'certificates/ocpp1/alm-ca-bundle-cert')}}"
  alm_username_password: "secrets/ergo_prod/alm-elk-username-password.yaml"
  alm_endpoint: 10.4.135.82
  alm_port: 9200
  label: ocpp2
  namespace: p2-ifrs17-itbb

# Cluster upgrade vars
raw_proxy_url: https://nexus.services.ergo/repository/raw-proxy

#Cluster health check variable
technical_user: 'secrets/ergo_prod_bz/LC_OCP_OPS_P2.yaml'
installer_artifacts_url: '{{ raw_proxy_url }}/pub/openshift-v4/clients/ocp'
nexus_cred_path: 'secrets/ergo_prod_bz/LC_NXRM_OSCP_P_001.yaml'


# Egress router
source:
  egress_ip1: 10.58.191.118
  egress_ip2: 10.58.191.117
  egress_gateway: 10.58.191.1
egress_destination: |
      25 tcp 10.4.112.28 25
      26 tcp 10.4.112.23 25
egress_service_ports: |
  - name: egress-smtp
    port: 25
    protocol: TCP
    targetPort: 25
  - name: egress-smtp2
    port: 26
    protocol: TCP
