domain_name: services.ergo
cluster_name: ocpp1
VMWARE_HOST: esxpe00900.servers.ergo
datacenter: PE0
datastore: PE0-C7-SC-SK4-N12ba-S
datastore_cluster: LDSC-PE0-C7-SC-SK4
vmware_cluster: PE0-C7-SC 
vcenter_cluster: PE0-C7-SC
rhcos_template: "rhcos-4.8.14-x86_64-vmware.x86_64-{{ datacenter }}"
vm_network: "dvPG-VM-10.4.127.0-PE0-01"
parent_folder: "/PE0/vm/Openshift Container Platform (OCP)"
vmare_cred_path: "secrets/ergo_prod/ergo_vmware_cred.yaml"
vm_rootdisk_size: 120
machine_cidr: "10.4.127.0/24"
network_utility_ip: 10.4.127.71
bootstrap_ip: 10.4.127.70
master_ips: 10.4.127.72,10.4.127.73,10.4.127.74
worker_ips: 10.4.127.78,10.4.127.79,10.4.127.80,10.4.127.81,10.4.127.82,10.4.127.83
infra_ips: 10.4.127.75,10.4.127.76,10.4.127.77
network_utility_netmask: 255.255.255.0
network_utility_gateway: 10.4.127.1
network_utility_dns_server: "{{ dns1 }}"
bootstrap_vm_name: "{{ cluster_name }}-bootstrap"
master_vm_names: "OCPPE0P11011,OCPPE0P11022,OCPPE0P11031"
worker_vm_names: "OCPPE0P12011,OCPPE0P12022,OCPPE0P12031,OCPPE0P12042,OCPPE0P12051,OCPPE0P12062"
infra_vm_names: "OCPPE0P16011,OCPPE0P16022,OCPPE0P16031"
pull_secret_path: "secrets/ergo_prod/pull_secret_ocpp1.yaml"
authorized_ssh_keys_path: "secrets/ergo_prod/LC_OCP_OPS_P1_ssh_keys.yaml"
auth_private_key_path: "secrets/ergo_prod/LC_OCP_OPS_P1_ssh_private_keys.yaml"
registry_fqdn: container-proxy.services.ergo
mirror_registry: "{{ registry_fqdn }}/openshift-release-dev/ocp-release"
mirror_registry_dev: "{{ registry_fqdn }}/openshift-release-dev/ocp-v4.0-art-dev"
haproxy_image: "{{ registry_fqdn }}/haproxytech/haproxy:latest"
httpd_image: "{{ registry_fqdn }}/rhel8/httpd-24:latest"
cluster_network: 10.128.0.0/14
host_prefix: 23
service_network: 172.30.0.0/16
master_vm_memory: 16384
worker_vm_memory: 65536
infra_vm_memory: 16384
master_vm_cpus: 8
worker_vm_cpus: 6
infra_vm_cpus: 8
domainname: linux.ergo
dns1: 10.4.112.37
dns2: 10.4.115.37
api_url: "https://api.{{ cluster_name }}.{{ domain_name }}:6443"
custom_url: "console.apps.{{ cluster_name }}.{{ domain_name }}"
ntpserver1: server 10.4.110.72 iburst
ntpserver2: server 10.4.110.69 iburst

# LDAP setup
bindDN: "LC_OCP_LDAP"
ldap_url: "ldaps://corp.ergo:636/DC=CORP,DC=ERGO?sAMAccountName"
bindPassword_path: "secrets/ergo_prod/bindpassword.yaml"

# LDAP Group Sync Cronjob
ldap_sync_url: "ldaps://corp.ergo:636"
groups_baseDN: "OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo"
#users_baseDN: "OU=Administration,OU=.Common,DC=corp,DC=ergo"
users_baseDN: "DC=corp,DC=ergo"
whitelist_groups: |
      CN=GFE_OCP_P1_CLUSTER_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo
      CN=GFE_OCP_P1_CLUSTER_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo	
      CN=GFE_OCP_P1_TEST_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo	
      CN=GFE_OCP_P1_TEST_EDIT,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo	
      CN=GFE_OCP_P1_TEST_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=ergo
ldap_sync_schedule: "*/15 * * * *"
ldap_sync_cli: "{{ registry_fqdn }}/openshift4/ose-cli:latest"
cluster_admin_group: GFE_OCP_P1_CLUSTER_ADMIN
cluster_reader_group: GFE_OCP_P1_CLUSTER_VIEW
##Certificates
root_cert_path: "certificates/CAs/root_ca_ergo.cer"
intermediate_cert_path: "certificates/CAs/sub_ca_ergo.cer"
api_cert_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.csr.cer"
apps_cert_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.csr.cer"
api_cert_key_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.key"
apps_cert_key_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.key"
quota_cpu: "5"
quota_memory: 30Gi
quota_pods: "100"
quota_configmaps: "20"
quota_persistentvolumeclaims: "0"
quota_replicationcontrollers: "80"
quota_requests_storage: 50Gi
quota_services: "30"
container_max_memory: 2Gi
container_min_memory: 128Mi
container_max_cpu: 4Gi
container_min_cpu: 100m
container_default_cpu: 200m
container_default_memory: 512Mi
container_defaultRequest_cpu: 1m
container_defaultRequest_memory: 256Mi
pod_max_memory: 8Gi
pod_min_memory: 6Mi
pod_max_cpu: 2000m
pod_min_cpu: 1m
vsphere_disk_format: zeroedthick
vsphere_sc_name: thick

##HaProxy variables
bootstrap:
 - name: ocpp1-bootstrap 
   ip: 10.4.127.70
controlplane:
 - name: OCPPE0P11011.ocpp1.services.ergo
   ip: 10.4.127.72
 - name: OCPPE0P11022.ocpp1.services.ergo
   ip: 10.4.127.73
 - name: OCPPE0P11031.ocpp1.services.ergo
   ip: 10.4.127.74
compute:
 - name: OCPPE0P12011.ocpp1.services.ergo
   ip: 10.4.127.78
 - name: OCPPE0P12022.ocpp1.services.ergo
   ip: 10.4.127.79
 - name: OCPPE0P12031.ocpp1.services.ergo
   ip: 10.4.127.80
 - name: OCPPE0P12042.ocpp1.services.ergo
   ip: 10.4.127.81
 - name: OCPPE0P12051.ocpp1.services.ergo
   ip: 10.4.127.82
 - name: OCPPE0P12062.ocpp1.services.ergo
   ip: 10.4.127.83
infra:
 - name: OCPPE0P16011.ocpp1.services.ergo
   ip: 10.4.127.75
 - name: OCPPE0P16022.ocpp1.services.ergo
   ip: 10.4.127.76
 - name: OCPPE0P16031.ocpp1.services.ergo
   ip: 10.4.127.77

vip_ip: 10.4.110.147
interface_name: 'ens192'
virtual_router_id: '115'

#Replace unhealthy node or create new node
replace_node_name: ''
new_node_name: ''
ip_address: ''
node_memory_mb: ''
node_cpu: ''
old_ignition_file: './files/old_worker.ign'
ignition_file: './files/worker.ign'

#ClusterLogForwarder Configuration for CLM/ALM
alm:
  alm_ca_bundle_cert: "{{lookup ('file', 'certificates/ocpp1/alm-ca-bundle-cert')}}"
  alm_username_password: "secrets/ergo_prod/alm-elk-username-password.yaml"
  alm_endpoint: 10.4.135.82
  alm_port: 9200
  label: ocpp1
  namespace: p1-ifrs17-itbb

# Cluster upgrade vars
raw_proxy_url: https://nexus.services.ergo/repository/raw-proxy

#Cluster health check variable
technical_user: 'secrets/ergo_prod/LC_OCP_OPS_P1.yaml'
installer_artifacts_url: '{{ raw_proxy_url }}/pub/openshift-v4/clients/ocp'
nexus_cred_path: 'secrets/ergo_prod/LC_NXRM_OSCP_P_001.yaml'


# Egress router
source:
  egress_ip1: 10.4.127.84
  egress_ip2: 10.4.127.85
  egress_gateway: 10.4.127.1
egress_destination: |
      25 tcp 10.4.112.28 25
      26 tcp 10.4.112.23 25
egress_service_ports: |
  - name: egress-smtp
    port: 25
    protocol: TCP
    targetPort: 25
  - name: egress-smtp2
    port: 26
    protocol: TCP

