domain_name: services.eden
cluster_name: ocpf1
VMWARE_HOST: esxte00900.servers.ergodev
datacenter: TE0
datastore: TE0-C7-SC-SK3-N12b6-S
datastore_cluster: LDSC-TE0-C7-SC-SK3
#datastore: LDSC-TE0-C7-SC-SK3
vmware_cluster: TE0-C7-SC
vcenter_cluster: TE0-C7-SC
rhcos_template: "rhcos-4.8.14-x86_64-vmware.x86_64-{{ datacenter }}"
vm_network: "dvPG-VM-EDEN-10.2.27.0-TE0-01"
parent_folder: "/TE0/vm/EDEN/Openshift Container Platform (OCP)"
vmare_cred_path: "secrets/eden_prod/eden_vmware_cred.yaml"
vm_rootdisk_size: 120
machine_cidr: "10.2.27.0/24"
network_utility_ip: 10.2.27.163
bootstrap_ip: 10.2.27.151
master_ips: 10.2.27.164,10.2.27.186,10.2.27.191
worker_ips: 10.2.27.240,10.2.27.241,10.2.27.250,10.2.27.251,10.2.27.252,10.2.27.253
infra_ips: 10.2.27.199,10.2.27.203,10.2.27.229
network_utility_netmask: 255.255.255.0
network_utility_gateway: 10.2.27.1
network_utility_dns_server: "{{ dns1 }}"
bootstrap_vm_name: "{{ cluster_name }}-bootstrap"
master_vm_names: "OCPIE0F11011,OCPIE0F11022,OCPIE0F11031"
worker_vm_names: "OCPIE0F12011,OCPIE0F12022,OCPIE0F12031,OCPIE0F12042,OCPIE0F12051,OCPIE0F12062"
infra_vm_names: "OCPIE0F16011,OCPIE0F16022,OCPIE0F16031"
pull_secret_path: "secrets/eden_prod/pull_secret_ocpf1.yaml"
authorized_ssh_keys_path: "secrets/eden_prod/authorized_ssh_keys-ocpf1.yaml"
auth_private_key_path: "secrets/eden_prod/LC_OCP_OPS_F1_ssh_private_keys.yaml"
registry_fqdn: container-proxy.services.eden
mirror_registry: "{{ registry_fqdn }}/openshift-release-dev/ocp-release"
mirror_registry_dev: "{{ registry_fqdn }}/openshift-release-dev/ocp-v4.0-art-dev"
haproxy_image: "{{ registry_fqdn }}/haproxytech/haproxy:latest"
httpd_image: "{{ registry_fqdn }}/rhel8/httpd-24:latest"
cluster_network: 10.128.0.0/14
host_prefix: 23
service_network: 172.30.0.0/16
master_vm_memory: 16384
worker_vm_memory: 65536
infra_vm_memory: 16384
master_vm_cpus: 8
worker_vm_cpus: 6
infra_vm_cpus: 8
domainname: linux.eden
dns1: 10.2.17.22
dns2: 10.2.17.23
api_url: "https://api.{{ cluster_name }}.{{ domain_name }}:6443"
custom_url: "console.apps.{{ cluster_name }}.{{ domain_name }}"
ntpserver1: server 10.2.17.125 iburst
ntpserver2: server 10.2.17.126 iburst
# LDAP setup
bindDN: "LC_OCP_LDAP"
ldap_url: "ldaps://corp.eden:636/DC=CORP,DC=EDEN?sAMAccountName"
bindPassword_path: "secrets/eden_prod/bindpassword.yaml"

# LDAP Group Sync Cronjob
ldap_sync_url: "ldaps://corp.eden:636"
groups_baseDN: "OU=Groups,OU=.Common,OU=IR,DC=corp,DC=eden"
#users_baseDN: "OU=Administration,OU=.Common,DC=corp,DC=eden"
users_baseDN: "DC=corp,DC=eden"
whitelist_groups: |
      CN=GFE_OCP_F1_CLUSTER_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=eden
      CN=GFE_OCP_F1_CLUSTER_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=eden	
      CN=GFE_OCP_F1_TEST_ADMIN,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=eden	
      CN=GFE_OCP_F1_TEST_EDIT,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=eden	
      CN=GFE_OCP_F1_TEST_VIEW,OU=Groups,OU=.Common,OU=IR,DC=corp,DC=eden      
ldap_sync_schedule: "*/15 * * * *"
ldap_sync_cli: "{{ registry_fqdn }}/openshift4/ose-cli:latest"
cluster_admin_group: GFE_OCP_F1_CLUSTER_ADMIN
cluster_reader_group: GFE_OCP_F1_CLUSTER_VIEW
##Certificates
root_cert_path: "certificates/CAs/root_ca_eden.crt"
intermediate_cert_path: "certificates/CAs/sub_ca_eden.cer"
api_cert_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.csr.cer"
apps_cert_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.csr.cer"
api_cert_key_path: "certificates/{{ cluster_name }}/api.{{ cluster_name }}.{{ domain_name }}.key"
apps_cert_key_path: "certificates/{{ cluster_name }}/apps.{{ cluster_name }}.{{ domain_name }}.key"
quota_cpu: "5"
quota_memory: 30Gi
quota_pods: "100"
quota_configmaps: "20"
quota_persistentvolumeclaims: "0"
quota_replicationcontrollers: "80"
quota_requests_storage: 50Gi
quota_services: "30"
container_max_memory: 2Gi
container_min_memory: 128Mi
container_max_cpu: 4Gi
container_min_cpu: 100m
container_default_cpu: 200m
container_default_memory: 512Mi
container_defaultRequest_cpu: 1m
container_defaultRequest_memory: 256Mi
pod_max_memory: 8Gi
pod_min_memory: 6Mi
pod_max_cpu: 2000m
pod_min_cpu: 1m
vsphere_disk_format: zeroedthick
vsphere_sc_name: thick

##HaProxy Variables
bootstrap:
 - name: ocpf1-bootstrap
   ip: 10.2.27.151

controlplane:
 - name: OCPIE0F11011.ocpf1.services.eden
   ip: 10.2.27.164
 - name: OCPIE0F11022.ocpf1.services.eden
   ip: 10.2.27.186
 - name: OCPIE0F11031.ocpf1.services.eden
   ip: 10.2.27.191

compute:
 - name: OCPIE0F12011.ocpf1.services.eden
   ip: 10.2.27.240
 - name: OCPIE0F12022.ocpf1.services.eden
   ip: 10.2.27.241
 - name: OCPIE0F12031.ocpf1.services.eden
   ip: 10.2.27.250
 - name: OCPIE0F12042.ocpf1.services.eden
   ip: 10.2.27.251
 - name: OCPIE0F12051.ocpf1.services.eden
   ip: 10.2.27.252
 - name: OCPIE0F12062.ocpf1.services.eden
   ip: 10.2.27.253

infra:
 - name: OCPIE0F16011.ocpf1.services.eden
   ip: 10.2.27.199
 - name: OCPIE0F16022.ocpf1.services.eden
   ip: 10.2.27.203
 - name: OCPIE0F16031.ocpf1.services.eden
   ip: 10.2.27.229

vip_ip: 10.2.27.189
interface_name: 'ens192'
virtual_router_id: '113'

#Replace unhealthy node or create new node
replace_node_name: ''
ip_address: ''
node_memory_mb: ''
node_cpu: ''
old_ignition_file: './files/old_worker.ign'

#ClusterLogForwarder Configuration for CLM/ALM
alm:
  alm_ca_bundle_cert: "{{lookup ('file', 'certificates/ocpf1/alm-ca-bundle-cert')}}"
  alm_username_password: "secrets/eden_prod/alm-f1-elk-username-password.yaml"
  alm_endpoint: 10.2.5.49
  alm_port: 9200
  label: ocpf1
  namespace: f1-ifrs17-itbb

# Cluster upgrade vars
raw_proxy_url: https://nexus.services.eden/repository/raw-proxy

#Cluster health check variable
technical_user: 'secrets/eden_prod/LC_OCP_OPS_F1.yaml'
installer_artifacts_url: '{{ raw_proxy_url }}/pub/openshift-v4/clients/ocp'
nexus_cred_path: 'secrets/eden_prod/LC_NXRM_OSCP_F_001.yaml'


# Egress router
source:
  egress_ip1: 10.2.27.20
  egress_ip2: 10.2.27.28
  egress_gateway: 10.2.27.1
egress_destination: |
      25 tcp 10.2.27.67 25
      26 tcp 10.2.27.68 25
egress_service_ports: |
  - name: egress-smtp
    port: 25
    protocol: TCP
    targetPort: 25
  - name: egress-smtp2
    port: 26
    protocol: TCP

