- name: Reboot host
  reboot:
    post_reboot_delay: 90
  when: patching == "os"
  become: yes

- name: Waiting for host to reboot
  wait_for_connection:
    delay: 60
    timeout: 300
  when: patching == "os"
  become: yes
