- name: Ensure /etc/haproxy directory exists
  file:
    path: /etc/haproxy
    state: directory

- name: update haproxy config
  template:
    src: haproxy.cfg.j2
    dest: /etc/haproxy/haproxy.cfg

- name: update selinux for port 6443
  seport:
    ports: 6443
    proto: tcp
    setype: http_port_t
    state: present

- name: update selinux for port 22623
  seport:
    ports: 22623
    proto: tcp
    setype: http_port_t
    state: present