- name: Create virtual machine
  vmware_guest:
    hostname: "{{ VMWARE_HOST }}"
    username: "{{ VMWARE_USER }}"
    password: "{{ VMWARE_PASSWORD }}"
    validate_certs: no
    datacenter: "{{ datacenter }}"
    cluster: "{{ vcenter_cluster }}"
    folder: "{{ parent_folder }}/{{ cluster_name }}"
    name: "{{ item.1|lower }}"
    state: present
    template: "{{ rhcos_template }}"
    disk:
    - size_gb: "{{ vm_rootdisk_size }}"
      type: thick
      datastore: "{{ datastore_cluster }}"
    networks:
    - name: "{{ vm_network }}"
    customvalues:
    - key: "disk.EnableUUID"
      value: "TRUE"
    hardware:
      memory_mb: "{{ memory }}"
      num_cpus: "{{ cpus }}"
  register: deploy

- name: Add new VM into Ansible inventories
  add_host:
    hostname: "{{ item.1|lower }}"
    groups:
    - openshift
    - "{{ node_role }}"
    ansible_host: "{{ item.0 }}"
    ansible_user: core
    vmware_uuid: "{{ deploy.instance.hw_product_uuid }}"
    mac_address: "{{ deploy.instance.hw_eth0.macaddress }}"

