- name: remove self-provisioner
  shell: oc patch clusterrolebinding.rbac self-provisioners -p '{"subjects"{{ ":" }} null}'
  register: result
  ignore_errors: yes
- debug: var=result

- name: remove cluster role from oauth self-provisioner
  shell: oc adm policy remove-cluster-role-from-group self-provisioner system:authenticated:oauth
  register: result
  ignore_errors: yes
- debug: var=result


- name: disable auto update
  #shell: oc patch clusterrolebinding.rbac self-provisioners -p '{"metadata":{"annotation":{"rbac.authorization.kubernetes.io/autoupdate":"false"}}}'
  shell: oc patch clusterrolebinding.rbac self-provisioners -p '{ "metadata"{{ ":" }} { "annotations"{{ ":" }} { "rbac.authorization.kubernetes.io/autoupdate"{{ ":" }} "false" } } }'
  register: result
  ignore_errors: yes
- debug: var=result

