- name: Disable Autoreboot
  shell: oc patch --type=merge --patch='{"spec":{"paused":true}}' machineconfigpool/master; oc patch --type=merge --patch='{"spec":{"paused":true}}' machineconfigpool/worker
  ignore_errors: yes
