- name: Ensure directory exists
  file:
    path: $HOME/merged
    state: directory
    recurse: yes
- name: remove files
  file:
    state: absent
    path: "{{ item }}"
  with_fileglob:
   - "~/merged/*"

- name: Copy certificates 
  copy:
    src: "{{ item }}"
    dest: '$HOME/merged/'
  with_items:
    - '{{ apps_cert_path }}'
    - '{{ root_cert_path }}'
    - '{{ intermediate_cert_path }}'
    
- name: Assemble from fragments from a directory
  assemble:
    src: '/$HOME/merged'
    dest: "/$HOME/merged-apps-cert.yaml"

- name: Convert merged cert to base64
  shell: base64 -w0  "/$HOME/merged-apps-cert.yaml"  > "/$HOME/merged-apps-64-cert.yaml"

- name: set fact
  set_fact:
    merged_apps_64: "{{ lookup('file', '/$HOME/merged-apps-64-cert.yaml') }}"


- name: replace the certs
  lineinfile:
    path: "secrets/kubeconfigs/{{ cluster_name }}/kubeconfig"
    regexp: '^    certificate-authority-data'
    line: "    certificate-authority-data: {{ merged_apps_64 }}"

- name: encrypt keys
  command: ansible-vault encrypt secrets/kubeconfigs/{{ cluster_name }}/kubeconfig --vault-password-file /$HOME/vaultfile

- name: remove files
  file:
    state: absent
    path: /$HOME/vaultfile
