#1. mkdir /secret/kubeconfig/cluster-name and delete content if existing old files
#2. fetch from utility new 
#3. replace certificate
#4. encrypt it
#5. delete kubeadmin password
- name: Ensure directory exists
  file:
    path: secrets/kubeconfigs/{{ cluster_name }}
    state: directory
    recurse: yes
  
- name: remove files
  file:
    state: absent
    path: "{{ item }}"
  with_fileglob:
   - "secrets/kubeconfigs/{{ cluster_name }}/kubeconfig*"

