#- name: print value_to_reuse
#  debug:
#    var: hostvars[item]['KUBEADMIN_PASSWORD']
#  with_items: "{{ groups['utility'] }}"
- name: login
  shell: oc login -u kubeadmin -p {{ hostvars[groups['utility'][0]]['KUBEADMIN_PASSWORD'] }} --server={{api_url}} --insecure-skip-tls-verify=true
  #no_log: true
  register: results3

- name: output "oc login command"
  debug:
    msg: "{{ results3.stdout }}"

- name: check login status
  shell: oc whoami;
  register: results2

- name: output "oc whoami command"
  debug:
    msg: "{{ results2.stdout }}"

