---
- hosts: localhost
  vars_prompt:
    - name: vault_password
      prompt: "Enter the vault password again to encrypt the kubeconfig:"
      private: yes
  vars:
    root_cert: "{{ lookup('file', '{{ root_cert_path }}') }}"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - include: tasks/kubeconfig-folder.yaml
    - name: Temporary write vault to file
      copy:
        content: '{{ vault_password }}'
        dest: "/$HOME/vaultfile"
    


- hosts: "{{ network_utility_ip }}"
  tasks:
  - name: Fetch the kubeconfig
    fetch:
      src: "{{ cluster_name }}/auth/kubeconfig"
      dest: "secrets/kubeconfigs/{{ cluster_name }}/kubeconfig"
      flat: yes

- hosts: localhost
  vars:
    root_cert: "{{ lookup('file', '{{ root_cert_path }}') }}"
    intermediate_cert: "{{ lookup('file', '{{ intermediate_cert_path }}') }}"
    apps_cer: "{{ lookup('file', '{{ apps_cert_path }}') }}"
  tasks:
    - include: tasks/kubeconfig-update.yaml
