---
- hosts: localhost
  vars:
    ssh_private_key:  "{{ lookup('file', '{{ auth_private_key_path }}') }}"
  vars_files:
    - "{{ nexus_cred_path }}"
  tasks:
    - include: tasks/auth-key.yaml
    - name: oc client tool
      include: tasks/oc-client.yaml

- hosts: "{{ network_utility_ip }}"
  tasks:
    - include: tasks/get_kubeadmin_cred.yaml

- hosts: localhost
  gather_facts: no
  tasks:
    - include: tasks/login-kubeadmin.yaml
    - name: Check cluster status
      include: tasks/check-cluster-n-vars.yaml

- hosts: ocp
  remote_user: core
  become: yes
  tasks:
    - name: change dns
      include: tasks/dns-update.yaml

- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - include: tasks/disable-autoreboot.yaml
    - include: tasks/restart-dns-sdn.yaml
    - name: Getting node details
      k8s_info:
        kind: node
        verify_ssl: no
      register: nodes

    - name: Set the variable for node details
      set_fact:
        node_names: "{{ nodes | json_query(query) }}"
      vars:
        query: "resources[].status.addresses[?type=='Hostname'].address[]"

    - name: Display node details
      debug:
        msg: "{{ node_names }}"
    - name: waiting for dns pods to be at ready state
      wait_for:
        timeout: 250
    - name: Check the openshift SDN
      include: tasks/check-sdn.yml
      with_items:
        - "{{ node_names }}"
    - include: tasks/custom-url.yaml
    - include: tasks/disable-selfprovisioning.yaml

- hosts: localhost
  vars:
    root_cert: "{{ lookup('file', '{{ root_cert_path }}') }}"
    intermediate_cert: "{{ lookup('file', '{{ intermediate_cert_path }}') }}"
    api_cer: "{{ lookup('file', '{{ api_cert_path }}') }}"
    apps_cer: "{{ lookup('file', '{{ apps_cert_path }}') }}"
    api_key: "{{ lookup('file', '{{ api_cert_key_path }}') }}"
    apps_key: "{{ lookup('file', '{{ apps_cert_key_path }}') }}"
  roles:
    - api-app-ssl
- hosts: localhost
  vars_files:
    - "{{ pull_secret_path }}"
    - "{{ alm.alm_username_password }}"
  vars:
    bindPassword: "{{ lookup('file', '{{ bindPassword_path }}') }}"
    root_cert: "{{ lookup('file', '{{ root_cert_path }}') }}"
    ansible_python_interpreter: /usr/bin/python3
  tasks:
    - include: tasks/approve-csr.yaml
    - include: tasks/etcd-encrypt.yaml
    - name: patch
      disable-selfprovisioning:
      register: result
      ignore_errors: yes
    - name: operators
      include: tasks/create-redhat-operator.yaml
    - include: tasks/ldap-config.yaml
    - include: tasks/ldap-group-sync.yaml
    - include: tasks/project-namespace-template.yaml
##    - include: tasks/group-sync-cron-run.yaml
    - include: tasks/cluster-role-to-group.yaml
    - include: tasks/disable-master-scheduler.yaml
    - include: tasks/image-registry-status.yaml
    - name: set variable for infra fqdn
      set_fact:
        infra_vm_fqdn: "{{ infra_vm_names.split(',') }}"
    - include: tasks/infranodes.yaml
    - include: tasks/move-ingress-pod-to-infra.yaml
    - include: tasks/storage-config.yaml
    - include: tasks/chrony-setup.yaml
    - include: tasks/disable-22623-22624port.yaml
    - name: configuring CRD for KubeletConfig
      include: tasks/kubeletconfig.yaml
    - include: tasks/ocp-roles.yaml
    - debug:
        msg: "Post installation Part1 task is completed. The cluster maybe UNREACHABLE for about 5 minutes . Machine config pool applying the changes and restarting the nodes"
    - include: tasks/enable-autoreboot.yaml
