---
- hosts: localhost
  tasks:
  - name: Include vmware credentials
    include_vars:
      file: secrets/eden_lab/eden_vmware_cred.yaml
      
  - name: vCenter Login
    uri:
      url: "https://{{VMWARE_HOST}}/rest/com/vmware/cis/session"
      force_basic_auth: yes
      method: POST
      user: "{{VMWARE_USER}}"
      password: "{{VMWARE_PASSWORD}}"
      status_code: 200
      validate_certs: no
    register: login

  - name: Get hosts from vCenter
    uri:
      url: "https://{{VMWARE_HOST}}/rest/vcenter/host"
      force_basic_auth: yes
      validate_certs: no
      headers:
        Cookie: "{{login.set_cookie}}"
    register: vchosts

  - name: snapshots
    vmware_guest_snapshot:
        datacenter: "{{ datacenter }}" 
        state: remove_all
        username: "{{VMWARE_USER}}"
        quiesce: false
        hostname: "{{VMWARE_HOST}}"
        memory_dump: false
        name: "{{ vm_name }}"
        folder: /"{{ datacenter }}"/"{{ vmware_cluster }}"
        password: "{{VMWARE_PASSWORD}}"
        validate_certs: no
        port: 443
    with_items: "{{vchosts.json.value}}"
      
      